### ISSUE TITLE
[Question / Feature Request] Screenshots vs Discord in-line text

### ISSUE THREAD

**Issue by boktai1000** [mikeStr8s/ClassicBot#10]
**Is your feature request related to a problem? Please describe.**
Not an issue/bug, but more of platform usability with the in-line text and hyperlinks.

**Describe the solution you'd like**
The ability to have a server-wide bot setting to configure the bot to post with Screenshots or In-line text. Something like `!classic settings screenshotoff` or whatever you would think an appropriate setting name toggle should be. I'm not sure the potential implications of having the Bot have to keep track of server specific settings.

**Describe alternatives you've considered**
Screenshots are a very clean approach, but maybe a way to also include a link to the associated item on Classic Wowhead, maybe by appending an extra value after the item such as `!classic item "Sulfuras, Hand of Ragnaros" link`

**Additional context**
Definitely dig the look of the screenshots, and I feel like there was probably a good reason to switch to them (Mobile users?). The only thing I see is the potential loss of information / usability in comparison to the in-line text. It might depend on how many of users are mobile vs desktop and how useful one style or the other may benefit your server (again, I'm assuming this was due to Mobile users or fixing some sort of formatting bug to make the output more predictable).

Please don't consider this as a negative, we aren't against the new style and it is very clean. I thing that including more information with the screenshots needs to be handled carefully if that's considered because it could quickly start to look very messy, or at least I could see that happening.

Curious what your thoughts are on this. As always thanks again for the great Bot, we still continue to enjoy using it while talking Classic - and look forward to your developments in the future!

P.S. I'll slow my roll on these questions / feature requests :)

**Comment by mikeStr8s** [comment]
Believe it or not, this is actually something I’ve thought of as well I realized once I had finished the new tooltip format that the user loses all of the utility of being able to click on item links, equip effects, etc.

I appreciate the feedback and will look into the application of server instance rules. I will also be looking into the addition of arguments as you’ve mentioned as well. Ease of use is the main goal for me, and including complex searches and arguments can tend to make things more difficult. I also want to make sure that my bot interaction is as fast as possible.

Please don’t stop coming up with ideas or questions. Continue to use and provide feedback on ClassicBot. I will be looking into opening an official Discord server for ClassicBot support so that there will be a more direct line to me and other users.

Thanks again!

**Comment by mikeStr8s** [comment]
Getting back into the swing of things I would like to tackle this issue. I continue to agree that the loss of information is almost detrimental to the use of the tool. Why show something if a person cannot then see it themselves in their own browser?

It is a lot to ask, but as a user what would your desired output consist of? If you find yourself with free time I would love to see any mockup or image that you believe would be a better output. I can only work from what I know, and as the developer I am always right ;) so you can see my predicament.

I will continue forward re-evaluating the embed format alongside the new image tooltip format. More input would be fantastic though.

Thanks

**Comment by shifuren** [comment]
Images are good format but losing ability to click link to see wowhead page is major drawback, would be nice to have link along with image too

**Comment by Road-block** [comment]
I'll add my support to this idea, my suggestion would be to use embeds so you can have the best of both worlds
Reference:  [embed object](https://discordapp.com/developers/docs/resources/channel#embed-object)
Example output: 
![item-embed](https://user-images.githubusercontent.com/109839/61054474-30f39f00-a3f8-11e9-8326-2c0359285678.png)
![item-embed-link](https://user-images.githubusercontent.com/109839/61054488-37821680-a3f8-11e9-8f90-c3d2ddb23210.png)

This is just the simplest embed object I made as  an example, you can add a lot of decorations.
```json
{"title":"Stockade Pauldrons", "url":"https://classic.wowhead.com/item=14552", "color":8388863, "image": {"url":"https://cdn.discordapp.com/attachments/586942253193494528/598865263835873299/26324634-8ed0-4909-b503-7bfde052fb10.png"}}
```

**Comment by mikeStr8s** [comment]
@Road-block I completely agree. I am planning on getting some of the tooltip stuff worked out and in the same vein I want to get your suggestion built in. I think that this is the cleanest way to present both an image and the link to the source. Thank your for a demonstration to work from.

**Comment by mikeStr8s** [comment]
With the recent rewrite of the bot and its functionality, this is now easier to implement and something I plan on doing. Just an update on the status of this

**Comment by mikeStr8s** [comment]
Active dev on this project is finished. I am sorry, but I have been pushed too far
