### ISSUE TITLE
Tooltip parser supplying incorrect output with command "!classic item whirlwind a"

### ISSUE THREAD

**Issue by mikeStr8s** [mikeStr8s/ClassicBot#11]
**Describe the bug**
Formatting and data inside tooltip for command `!classic item whirlwind a` is incorrect. The text and formatting is wrong and seems to have carried over template HTML.

**To Reproduce**
1. Go to channel with ClassicBot enabled
2. Type command `!classic item whirlwind a`
3. Wait for return
4. See incorrect tooltip

**Expected behavior**
When doing a partial search, in this case for whirlwind axe, the search should return a tooltip for the first matched item in propper format. There should be no HTML intermixed into the tooltip and it should be human readable

**Screenshots**
![image](https://user-images.githubusercontent.com/10874994/57226181-6507a980-6fdc-11e9-8ec6-4f3b28eebd84.png)

**Comment by Kaitology** [comment]
Would like to add:

![image](https://user-images.githubusercontent.com/50146411/57229219-d152cf00-7015-11e9-8676-6d7aea3aadf3.png)


The tooltip is cut off in width.

**Comment by mikeStr8s** [comment]
The original source of the issue here has been fixed in the dev branch. I am closing this issue on the base that the bug is squashed. I am however going to be opening an issue up for the formatting and clipping that is happening to the image. Thank you
