### ISSUE TITLE
!classic item does not comply with parser structure. 

### ISSUE THREAD

**Issue by mfcRogue** [mikeStr8s/ClassicBot#14]
**Describe the bug**
Try to use !classic item, should show the item, however comes up with items does not comply with parser structure

**To Reproduce**
1. !classic item Mallet of Zul'Farrak or Workshop Key  or Scarlet Key
2: Receive error  item Mallet of Zul'Farrak does not comply with parser structure. Please refine search if this was not the Mallet of Zul'Farrak that was intended.
If you believe this to be an error, please submit an issue here: 

**Expected behavior**
Correct display of item(s)

**Comment by mikeStr8s** [comment]
Thank you for bringing this to my attention. I will be looking into this.

**Comment by mikeStr8s** [comment]
Fixed in dev branch. This did however expose a render bug that I need to fix. The items mentioned now return results.
