### ISSUE TITLE
Different item appearance (Wowhead style)

### ISSUE THREAD

**Issue by Vipeax** [mikeStr8s/ClassicBot#18]
I've generated PNGs for every image in the game in the style of Wowhead:
https://items.classicmaps.xyz/ (archive is available at the bottom)

Perhaps it may help you if you would be willing feed them from a website/API (you can even hard-link them from my website if you want; it can handle it easily). This idea popped up after a friend of mine invited your bot to our Discord, but they appeared 'too plain' for my liking. If you prefer the current method and/or style then feel free to ignore this 'feature request'.

Oh and the idea for pre-rendered images originates from the principle that we know what items will be available in the game.

**Comment by mikeStr8s** [comment]
This is actually a real help. I will likely continue to use WoWHead for searching, but if the item tooltip id's match the tooltips in your archive then I will be moving forward with gathering those instead of generating my own. It is cleaner and nicer to just have them straight from a source.

**Comment by aikaterna** [comment]
Sorry for piggybacking on this issue to ask this, but would you be willing to generate spell images as well @Vipeax ? The images you generated for the items are excellent.

**Comment by mikeStr8s** [comment]
This has been implemented
