### ISSUE TITLE
Searching for "The 1 Ring"

### ISSUE THREAD

**Issue by Shyfty** [mikeStr8s/ClassicBot#19]
I found that any attempt at searching The 1 Ring returned the item "Alex's Ring of Audacity"

It's the only error we've found and I started to wonder if it's an Easter egg, making fun of the "Audacity" of anyone who dares search for the 1 Ring. If that is an Easter Egg, I applaud you. If not, it's a hell of a funny coincidence.

Shyfty

**Comment by Reebz** [comment]
Confirming the bug, but we get Bonescythe Ring as the returned item.

**Comment by Shyfty** [comment]
I can confirm that as well- testing again now and we no longer get the Ring of Audacity and instead it returns the Bonescythe Ring every time.

Tried getting it to pull up the Ring of Audacity, which it will no longer find.

**Comment by mikeStr8s** [comment]
This is an odd occurance, and I enjoyed reading that you thought me clever enough to include such an easter egg. This will be investigated.

**Comment by mikeStr8s** [comment]
I believe this issue to be resolved. 
![image](https://user-images.githubusercontent.com/10874994/66485568-0c4ea800-ea77-11e9-9978-02600613ec94.png)

Hopefully, the bot continues to work for you two.
