### ISSUE TITLE
Doesn’t respond to anything but !classic and only half the time

### ISSUE THREAD

**Issue by Hoodai** [mikeStr8s/ClassicBot#22]
**Describe the bug**
On some discords, Classic Bot doesn’t respond to any commands other than just “!classic”. An example of a broke command is “!classic item training sword”.

**Screenshots**
![917FA473-A707-4FAA-9CCD-729D272177F0](https://user-images.githubusercontent.com/3504768/63301811-1935f300-c2a1-11e9-8bba-c3916633dfd2.png)

**Comment by mikeStr8s** [comment]
On my personal Discord and the ClassicBot Discord, there seems to be no issue. It could have something to do with permissions allowed to the bot. I have not done any testing with restrictions and the like on my bot. I apologize, but because I cannot recreate this I am not sure how I am to help :(

**Comment by Hoodai** [comment]
I tested permissions and the bot doesn’t run without administrator. I’m a little curious why this is required by the bot when all its functions are summarized in other permissions.

**Comment by Hoodai** [comment]
Deeper inspection shows that the bot actually requests the channel-specific permission “Attach Files” in every channel that you want to use it.

Maybe this could be added to the readme?

**Comment by mikeStr8s** [comment]
Yeah, with the way tooltips currently work that is necessary. I will add to the readme. I am working on ways to remove this requirement though. Just finding time to make the changes is becoming more and more difficult. See #18 for more information on how I would like to change it.

**Comment by mikeStr8s** [comment]
Readme will be updated to display that the bot needs to be allowed to attach files.
