### ISSUE TITLE
Partial matches

### ISSUE THREAD

**Issue by Kaitology** [mikeStr8s/ClassicBot#3]
**Is your feature request related to a problem? Please describe.**
The bot is pretty useless when you need to fill in exact item name matches. 

**Describe the solution you'd like**
Allow partial text matching. 
!item Giantstalker boot should return Giantstalker's Boots 
!item Giantstalker should just return the first item you encounter or in a perfect world a link to the item set: https://www.wowhead.com/item-set=206/giantstalker-armor

**Describe alternatives you've considered**
None.

**Additional context**
Loving the bot so far, if the partial name issue gets fixed it would be a massive improvement.

**Comment by mikeStr8s** [comment]
This Feature is being explored at length. I want to make sure that it works well and that it covers all bases. I still believe that exact text matching is important, that is the way that it works in game and that is how I wanted it to work initially.

**Implementation Ideas:**

1. Maintain strict searching and have "lazy" search modifier that flags a search as lazy to return the first instance of the search term.

2. Make search strict but if there is no direct match then provide the next most closest result.

3. All search is lazy by default and all results are returned in a list and the bot awaits user input to select the correct option in the list.

There are plenty of options on how to better implement the search. Once I am done bug hunting, this will be one of the more important feature additions.

Thank you for your support and your suggestion.

**Comment by mikeStr8s** [comment]
Feature added in #8 

closing issue
