### ISSUE TITLE
Some abilities / items fail silently

### ISSUE THREAD

**Issue by boktai1000** [mikeStr8s/ClassicBot#4]
Examples include:

- !ability Crusader
- !ability "Greater Blessing of Kings"
- !talent blessing of kings
- !item Formula: Enchant Bracers - Superior Stamina

Post here: https://www.reddit.com/r/classicwow/comments/bir4rr/i_made_a_discord_bot_for_classic_wow_that/em8fi91/

Thank you for the work on this! Our server has been enjoying it, and thought I'd just let you know a couple of oddities we ran into.

**Comment by mikeStr8s** [comment]
I am currently in the process of completely reworking the search feature. I hope to have this new search be better and more transparent on how or why something failed. I also want to be able to increase general stability by rethinking my hosting solution. These combined should hopefully fix many of the issues associated with how the search functions.

Thank you for your feedback and I will make sure to add those items to my testing suite to make sure that nothing fails silently in the future.

**Comment by mikeStr8s** [comment]
Added many more instances of error handling in #8 This issue will be closed for now, but will reopen or be modified into another issue depending on the bug present.
